language: cpp
env:
  matrix:
    - TARGET: ut ut-valgrind
      TYPE: Debug
    - TARGET: perf
      TYPE: Release
addons:
  apt:
    packages:
      - valgrind
      - ninja-build
before_install:
  - uname -a
  - lsb_release -a
install:
  - cd cpp-app/testing
  - ./install-dependencies.sh
script:
  - cd cpp-app/testing
  - mkdir build && cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=$TYPE ..
  - ninja $TARGET
notifications:
  email: false
