#!/usr/bin/env python3

import os
import sys
import resource
import subprocess
from py.path import local as pypath

def find_output():
    pairs = [a for a in zip(sys.argv, sys.argv[1:])]
    return next(p[1] for p in pairs if p[0] == '-o')

def time_str(name):
    attrs = ['ru_utime', 'ru_stime', 'ru_maxrss', 'ru_ixrss', 'ru_idrss']
    info = resource.getrusage(resource.RUSAGE_CHILDREN)
    wall = '%s %.3f' % (name, info.ru_utime + info.ru_stime)
    stats = ''.join(['%-10s %s\n' % (a, getattr(info, a)) for a in attrs])
    return wall + '\n\n' + stats

def cmd_str():
    curdir = os.path.abspath(os.curdir)
    cmd = ' '.join(sys.argv).replace('"', '\\"')
    return '(cd %s && %s)\n' % (curdir, cmd)

def parse_includes(preproc):
    includes = set()
    for line in filter(lambda x: x.startswith('#'), preproc.decode().splitlines()):
        if 'include' in line:
            include = line.split()[2].strip('"')
            includes.add(include)
    return ''.join(['%s\n' % x for x in sorted(includes)])

sys.argv[0] = '/usr/bin/g++'
root_dir = pypath('/tmp/gcclog').ensure_dir()
output = find_output()

if '-c' in sys.argv:
    gee_dir = pypath.make_numbered_dir(prefix='compile-', rootdir=root_dir, keep=0)
    cplt = subprocess.run(sys.argv)
    gee_dir.join('stat').write('\n'.join([time_str(sys.argv[-1]), cmd_str()]))

    sys.argv = [a.replace(output, '/dev/stdout') for a in sys.argv] + ['-E']
    includes_cplt = subprocess.run(sys.argv, stdout=subprocess.PIPE)
    gee_dir.join('include').write('\n'.join([parse_includes(includes_cplt.stdout)]))
else:
    gee_dir = pypath.make_numbered_dir(prefix='link-', rootdir=root_dir, keep=0)
    cplt = subprocess.run(sys.argv)
    gee_dir.join('stat').write('\n'.join([time_str(output), cmd_str()]))

sys.exit(cplt.returncode)
