#!/usr/bin/env python3

import os
import sys
import resource
import subprocess
from py.path import local as pypath

def time_str(name):
    attrs = ['ru_utime', 'ru_stime', 'ru_maxrss', 'ru_ixrss', 'ru_idrss']
    info = resource.getrusage(resource.RUSAGE_CHILDREN)
    wall = '%s %.3f' % (name, info.ru_utime + info.ru_stime)
    stats = ''.join(['%-10s %s\n' % (a, getattr(info, a)) for a in attrs])
    return wall + '\n\n' + stats

def cmd_str():
    return ' '.join(sys.argv)

sys.argv[0] = '/usr/bin/g++'
root_dir = pypath('/tmp/gcclog').ensure_dir()

if '-c' in sys.argv:
    gee_dir = pypath.make_numbered_dir(prefix='compile-', rootdir=root_dir, keep=0)
    cplt = subprocess.run(sys.argv)
    gee_dir.join('stat').write('\n'.join([time_str(sys.argv[-1]), cmd_str()]))
else:
    gee_dir = pypath.make_numbered_dir(prefix='unknown-', rootdir=root_dir, keep=0)
    cplt = subprocess.run(sys.argv)
    gee_dir.join('stat').write('\n'.join([cmd_str()]))

sys.exit(cplt.returncode)

# TODO: if compiling add list of includes
# TODO: add linking stats
