#!/usr/bin/env python

import os
import sys
import re

def read_into_table(fileobj):
    lines = []
    pattern = re.compile('\s+')
    for line in fileobj:
        x, y, z = pattern.split(line, 2)
        lines.append((x, y, z.rstrip()))
    return lines

def max_node_len(lines):
    return max((len(node) for node, _, _ in lines))

def fmt_time_align(lines):
    return "{0:%ss} {1} {2}" % max_node_len(lines)

def print_all(lines, fmt):
    for node, tst, log in lines:
        print fmt.format(node, tst, log)

lines = read_into_table(open('enb'))
lines.sort(key=lambda x: x[1])
print_all(lines, fmt_time_align(lines))

#for line in lines:
#    print line

#import pdb;pdb.set_trace()

#for x in sys.stdin:

#for line in open("enb"):
#    x, y, z = re.split('\s+', line, 2)
#    lines.append((x, y, z.rstrip()))

#for line in open("enb"):
#    import pdb;pdb.set_trace()
#    lines.append(line.split())

