#!/bin/bash -e

PROGRAM=$(basename "$0")
USAGE="usage: "$PROGRAM" [-d|--dir dirname] <filename> [<filename> ...]"

die () {
    echo "${PROGRAM}: $@"
    exit 1
}

usage () {
    echo "$USAGE"
    exit 0
}

[ $# == 0 ] && usage

export DIR=
export INPUTS=

while [ $# != 0 ]
do
	case "$1" in
        -h|--help)
            usage
            ;;
	    -d|--dir)
            [ $# -lt 2 ] && die "no dir argument"
            DIR="$2"
            shift 2
            ;;
	    *)
            [ ! -f $1 ] && die "file not found" $1
            INPUTS="$INPUTS $1"
            shift
            ;;
	esac
done

[ -z ${DIR} ] && die "no output dir"
[ ! -d ${DIR} ] && mkdir ${DIR}

export tmp=$(mktemp /tmp/${PROGRAM}.XXXXXX)
trap "{ rm -f "$tmp"; exit 255; }" EXIT

cat ${INPUTS} | dos2unix | cut -d' ' -f'8-' > "$tmp"
nodes=$(cat "$tmp" | cut -d' ' -f'1' | sort -u | grep -v '^$')
echo "$nodes" | parallel 'cat "$tmp" | grep "^{} " | cut -d" " -f"2-" > "${DIR}/{}"'

