#!/bin/bash

PROGRAM=$(basename "$0")
USAGE="Usage: $PROGRAM [options] <filename> [<filename> ...]
Options:
    [-d|--dir dirname]             output dir, will create if doesn't exist
    [-f|--filter-nodes regex]      regular expression to filter nodes
    [-n|--dry-run]                 just show found nodes"

die () {
    echo "${PROGRAM}: $@"
    exit 1
}

usage () {
    echo "$USAGE"
    exit 0
}

[ $# == 0 ] && usage

export DIR=
export INPUTS=
export FILTER=
export DRYRUN=

while [ $# != 0 ]
do
	case "$1" in
        -h|--help)
            usage
            ;;
	    -d|--dir)
            [ $# -lt 2 ] && die "no dir name"
            DIR="$2"
            shift 2
            ;;
	    -f|--filter-nodes)
            [ $# -lt 2 ] && die "no filter command"
            FILTER="$2"
            shift 2
            ;;
	    -n|--dry-run)
            DRYRUN=1
            shift
            ;;
	    *)
            [ ! -f $1 ] && die "file not found" $1
            INPUTS="$INPUTS $1"
            shift
            ;;
	esac
done

orig_pattern () {
    local i="[\d]+"
    local x="[\da-f]+"
    local a="[^\s]+"
    local s="[\s]+"
    local d="\."
    echo "^$i$s$i$d$i$s$i:$i:$i$d$i$s\[$i$d$i$d$i$d$i\]$s$x$s$a$s<$a>"
}

nodetime_pattern () {
    local a="[^\s]+"
    local s="[\s]+"
    echo "^$a$s<$a>"
}

check_orig () {
    [ $(head $1 -n 100 | grep -P "$(orig_pattern)" -c) != 0 ]
}

check_nodetime () {
    [ $(head $1 -n 100 | grep -P "$(nodetime_pattern)" -c) != 0 ]
}

validate_inputs() {
    for x
    do
        check_orig $x && continue
        check_nodetime $x && continue
        die "unknown file format:" $x
    done
}

combine_tmp() {
    export tmp=$(mktemp /tmp/${PROGRAM}.XXXXXX)
    trap "{ rm -f $tmp; exit 255; }" EXIT
    for x
    do
        check_orig $x && cut -d' ' -f'8-' $x | dos2unix | grep -v '^$' >> "$tmp"
        check_nodetime $x && cat $x >> "$tmp"
    done
}

extract_nodes() {
    local nodes=$(cut -d' ' -f'1' "$tmp" | uniq | sort -u)
    [ "$FILTER" ] && nodes=$(echo "$nodes" | grep -P "$FILTER")
    echo "$nodes"
}

validate_inputs ${INPUTS}
combine_tmp ${INPUTS}

if [ "$DRYRUN" ]
then
    echo "$(extract_nodes)"
    exit 0
fi

if [ ${DIR} ]
then
    [ ! -d ${DIR} ] && mkdir ${DIR}
    echo "$(extract_nodes)" |
        parallel 'awk -v N="{}" '"'"'
            { if ($1 == N) print substr($0, index($0, $2)) }
        '"'"' $tmp > "${DIR}/{}"'
else
    maxlen=$(echo "$(extract_nodes)" | wc -L)
    awk -v F="${FILTER}" -v M="$maxlen" '
            { if (match($1, F)) { printf "%-"M"s ", $1; print substr($0, index($0, $2)) } }
        ' $tmp
fi

# todo:
# 1. sort by n-th column (and then learn to custom sort timestamps)
# 2. timestamp aligned vertically
# 3. make a stat output in split (5 columns, sorting)
# *. --since
# *. --until
# *. --no-timestamp
# *. --stat
# *. --filter-logs
